<?php

namespace DP\VoipServer\VoipServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MumbleServerEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoipServerEntityRepository extends EntityRepository{
    
}