imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    
parameters:
    sonata.user.form.type.security_roles.class: Sonata\UserBundle\Form\Type\SecurityRolesType

    sonata.user.profile.form.type.class:            Sonata\UserBundle\Form\Type\ProfileType
    sonata.user.profile.form.handler.default.class: Sonata\UserBundle\Form\Handler\ProfileFormHandler

    sonata.user.admin.user.class:              Application\Sonata\UserBundle\Admin\Entity\UserAdmin
    sonata.user.admin.user.controller:         SonataAdminBundle:CRUD
    sonata.user.admin.user.translation_domain: SonataUserBundle

    sonata.user.admin.group.class:              Sonata\UserBundle\Admin\Entity\GroupAdmin
    sonata.user.admin.group.controller:         SonataAdminBundle:CRUD
    sonata.user.admin.group.translation_domain: %sonata.user.admin.user.translation_domain%

    sonata.user.admin.groupname: sonata_user

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale
    trust_proxy_headers: false
    session:          ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources: ['::form.html.twig']

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        []
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
          json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    profile:  # Authentication Form
      form:
          type:               app_user_profile
          name:               app_user_profile_form
          validation_groups:  [Authentication] # Please note : this is not the default value

sonata_user:
    security_acl: true
    impersonating_route: _welcome
    class:
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group

    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]

sonata_admin:
    security:
        handler: sonata.admin.security.handler.acl
        information:
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]
    templates:
        layout: ::layout-sonata.html.twig
#        layout: SonataAdminBundle::standard_layout.html.twig
    dashboard:
        groups:
            sonata_user:
                items: [sonata.user.admin.user, sonata.user.admin.group]
                label: admin.group.user
            dp_game:
                items: [dp.game.admin.game, dp.game.admin.plugin]
                label: admin.group.game
    persist_filters: true

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
