parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: dpb4_sf
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 53e8b1f2a87f0c89e4e855aa76f7d5e41556ba33
    database_path: null
