# Copyright (C) 2010-2012 Kerouanton Albin, Smedts Jérôme
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

DPGameServerBundle:
    resource: "@DPGameServerBundle/Resources/config/routing.yml"
    prefix:   /game/

DPMachineBundle:
    resource: "@DPMachineBundle/Resources/config/routing.yml"
    prefix:   /machine/

ApplicationSonataUserBundle:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix: /
    
DPMumbleServerBundle:
    resource: "@DPMumbleServerBundle/Resources/config/routing.yml"
    prefix:   /mumble/

_welcome:
    pattern: /
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal