server:
    pattern:  /
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:index" }

server_show:
    pattern:  /show
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:show" }

server_user:
    pattern:  /new
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:new" }

server_create:
    pattern:  /create
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:create" }

server_edit:
    pattern:  /edit
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:edit" }

server_update:
    pattern:  /update
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:update" }

server_delete:
    pattern:  /delete
    defaults: { _controller: "DPMumbleServerBundle:MumbleServer:delete" }
