<?php

namespace DP\VoipServer\MumbleServerBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * MumbleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MumbleRepository extends EntityRepository
{
}
