parameters:
    mumble.factory.class:         DP\VoipServer\MumbleServerBundle\service\MumbleFactory
#    mumble.virtualServer.class:   DP\VoipServer\MumbleServerBundle\Ice\VirtualServer\VirtualServer
#    mumble.virtualUser.class:     DP\VoipServer\MumbleServerBundle\Ice\VirtualServer\VirtualUser
#    mumble.ice.class:             DP\VoipServer\MumbleServerBundle\Ice\Ice
#    mumble.meta.class:            DP\VoipServer\MumbleServerBundle\Ice\Meta

services:
  mumble.factory:
    class:  "%mumble.factory.class%"