services:
    newsletter_manager:
        class:          DP\VoipServer\MumbleServerBundle\Ice\Ice
        factory_class:  DP\VoipServer\MumbleServerBundle\service\MumbleFactory
        factory_method: getConnection