# Copyright (C) 2010-2012 Kerouanton Albin, Smedts Jerome
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

user_menu:
    pattern: /
    defaults: { _controller: ApplicationSonataUserBundle:User:homeMenu }

config_menu:
    pattern: /menu/config
    defaults: { _controller: ApplicationSonataUserBundle:User:configMenu }

# Réécrit la route sonata pour ne pas afficher une page non charté
# L'utilisateur est redirigé vers la home
sonata_user_profile_show:
    pattern: /profile/
    defaults: { _controller: ApplicationSonataUserBundle:Profile:show }
    requirements: { _method: GET }


# contient la route pour le /login, important
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# les routes pour l'inscription (inscription, confirmation email, etc.)
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
# les routes pour redefinir son mot de passe (envoi du mail, etc.)
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
# les routes pour les profils utilisateurs (voir et editer un profil)
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# une route pour changer de mot de passe
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password